server:
  port: 8081

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dbAuth
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1