spring:
  main:
    allow-circular-references: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:maindb

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: batchHomework