server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dbOrders
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:app.pub

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

openapi:
  service:
    title: order-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /order-service/v3/api-docs
  swagger-ui:
    path: /order-service/swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - refresh
    enabled-by-default: false
