spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodbHomework

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concert:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR