spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
  file:
    name: ./logs/library.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/library.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB